const Product = require('../models/product');
const mongoose = require('mongoose');

const db = 'mongodb://localhost:27017/icanstore';

mongoose.connect(db, { useNewUrlParser: true });

var products = [
  new Product({
    prod_Name: 'Admin Set - 20 Drop - Adult',
    prod_Code: '1',
    prod_NAPI: '',
    prod_Description: 'Admin Set - 20 Drop - Adult',
    prod_Pk_Qty: 1,
    prod_Price: 8.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Alpha Pore Wound Dressing 8 cm x 6 cm',
    prod_Code: '299589 - 001',
    prod_NAPI: '299589 - 001',
    prod_Description: 'Alpha Pore Wound Dressing 8 cm x 6 cm',
    prod_Pk_Qty: 1,
    prod_Price: 2.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Alpha Pore Wound Dressing 8cm x 15cm',
    prod_Code: '299588-001',
    prod_NAPI: '299588-001',
    prod_Description: 'Alpha Pore Wound Dressing 8cm x 15cm',
    prod_Pk_Qty: 1,
    prod_Price: 4.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Alpha Pore Wound Dressing 20 cm x 10 cm',
    prod_Code: '299587-001',
    prod_NAPI: '299587-001',
    prod_Description: 'Alpha Pore Wound Dressing 20 cm x 10 cm',
    prod_Pk_Qty: 1,
    prod_Price: 5.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Alpha Post-Op Dressing 6.5cm x 5cm',
    prod_Code: '1002872-001',
    prod_NAPI: '1002872-001',
    prod_Description: 'Alpha Post-Op Dressing 6.5cm x 5cm',
    prod_Pk_Qty: 1,
    prod_Price: 5.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Alpha Post - Op Dressing 8 cm x 9 cm',
    prod_Code: '100287-301',
    prod_NAPI: '100287-301',
    prod_Description: 'Alpha Post - Op Dressing 8 cm x 9 cm',
    prod_Pk_Qty: 1,
    prod_Price: 7.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Alpha Post-Op Dressing 15cm x 8cm',
    prod_Code: '1002870-001',
    prod_NAPI: '1002870-001',
    prod_Description: 'Alpha Post-Op Dressing 15cm x 8cm',
    prod_Pk_Qty: 1,
    prod_Price: 13.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Alpha Post - Op Dressing 25 cm x 10 cm',
    prod_Code: '1002871-001',
    prod_NAPI: '1002871-001',
    prod_Description: 'Alpha Post - Op Dressing 25 cm x 10 cm',
    prod_Pk_Qty: 1,
    prod_Price: 16.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Adhesive Sports  50mm x 4.5m',
    prod_Code: '1002387-001',
    prod_NAPI: '1002387-001',
    prod_Description: 'Bandage - Adhesive Sports  50mm x 4.5m',
    prod_Pk_Qty: 1,
    prod_Price: 31.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Adhesive Sports 75 mm x 4.5 m',
    prod_Code: '1002388-001',
    prod_NAPI: '1002388-001',
    prod_Description: 'Bandage - Adhesive Sports 75 mm x 4.5 m',
    prod_Pk_Qty: 1,
    prod_Price: 39.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Conforming 50mm x 4m',
    prod_Code: '299592-001',
    prod_NAPI: '299592-001',
    prod_Description: 'Bandage - Conforming 50mm x 4m',
    prod_Pk_Qty: 1,
    prod_Price: 3.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Conforming 75 mm x 4 m',
    prod_Code: '299593-001',
    prod_NAPI: '299593-001',
    prod_Description: 'Bandage - Conforming 75 mm x 4 m',
    prod_Pk_Qty: 1,
    prod_Price: 4.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Conforming 100mm x 4m',
    prod_Code: '299590-001',
    prod_NAPI: '299590-001',
    prod_Description: 'Bandage - Conforming 100mm x 4m',
    prod_Pk_Qty: 1,
    prod_Price: 5.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Conforming 150 mm x 4 m',
    prod_Code: '299591-001',
    prod_NAPI: '299591-001',
    prod_Description: 'Bandage - Conforming 150 mm x 4 m',
    prod_Pk_Qty: 1,
    prod_Price: 6.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Elastic  50mm x 4.5m',
    prod_Code: '1002187-001',
    prod_NAPI: '1002187-001',
    prod_Description: 'Bandage - Elastic  50mm x 4.5m',
    prod_Pk_Qty: 1,
    prod_Price: 23.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Elastic 75 mm x 4.5 m',
    prod_Code: '1002188-001',
    prod_NAPI: '1002188-001',
    prod_Description: 'Bandage - Elastic 75 mm x 4.5 m',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Elastic 100mm x 4.5m',
    prod_Code: '1002185-001',
    prod_NAPI: '1002185-001',
    prod_Description: 'Bandage - Elastic 100mm x 4.5m',
    prod_Pk_Qty: 1,
    prod_Price: 38.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Elastic 150 mm x 4.5 m',
    prod_Code: '1002186-001',
    prod_NAPI: '1002186-001',
    prod_Description: 'Bandage - Elastic 150 mm x 4.5 m',
    prod_Pk_Qty: 1,
    prod_Price: 49.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Tubular Size B',
    prod_Code: '1002189-001',
    prod_NAPI: '1002189-001',
    prod_Description: 'Bandage - Tubular Size B',
    prod_Pk_Qty: 1,
    prod_Price: 12.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Tubular Size C',
    prod_Code: '100219-001',
    prod_NAPI: '100219-001',
    prod_Description: 'Bandage - Tubular Size C',
    prod_Pk_Qty: 1,
    prod_Price: 13.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Tubular Size D',
    prod_Code: '1002191-001',
    prod_NAPI: '1002191-001',
    prod_Description: 'Bandage - Tubular Size D',
    prod_Pk_Qty: 1,
    prod_Price: 14.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Tubular Size E',
    prod_Code: '1002982-001',
    prod_NAPI: '1002982-001',
    prod_Description: 'Bandage - Tubular Size E',
    prod_Pk_Qty: 1,
    prod_Price: 15.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Bandage - Tubular Size F',
    prod_Code: '1002983-001',
    prod_NAPI: '1002983-001',
    prod_Description: 'Bandage - Tubular Size F',
    prod_Pk_Qty: 1,
    prod_Price: 16.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cervical Collar - Small',
    prod_Code: '1011178-001',
    prod_NAPI: '1011178-001',
    prod_Description: 'Cervical Collar - Small',
    prod_Pk_Qty: 1,
    prod_Price: 69.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cervical Collar - Medium',
    prod_Code: '1011175-001',
    prod_NAPI: '1011175-001',
    prod_Description: 'Cervical Collar - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 69.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cervical Collar - Large',
    prod_Code: '1011173-001',
    prod_NAPI: '1011173-001',
    prod_Description: 'Cervical Collar - Large',
    prod_Pk_Qty: 1,
    prod_Price: 69.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cotton Buds',
    prod_Code: 'NO CODE NEEDED',
    prod_NAPI: '',
    prod_Description: 'Cotton Buds',
    prod_Pk_Qty: 100,
    prod_Price: 5.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cotton Buds',
    prod_Code: 'NO CODE NEEDED',
    prod_NAPI: '',
    prod_Description: 'Cotton Buds',
    prod_Pk_Qty: 200,
    prod_Price: 8.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cotton Wool Balls Coloured',
    prod_Code: 'NO CODE NEEDED',
    prod_NAPI: '',
    prod_Description: 'Cotton Wool Balls Coloured',
    prod_Pk_Qty: 100,
    prod_Price: 22.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cotton Wool Balls White',
    prod_Code: 'NO CODE NEEDED',
    prod_NAPI: '',
    prod_Description: 'Cotton Wool Balls White',
    prod_Pk_Qty: 100,
    prod_Price: 19.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Dressing Tray',
    prod_Code: 'NO CODE NEEDED',
    prod_NAPI: '',
    prod_Description: 'Dressing Tray',
    prod_Pk_Qty: 1,
    prod_Price: 10.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Emergency Blanket',
    prod_Code: '1011157-001',
    prod_NAPI: '1011157-001',
    prod_Description: 'Emergency Blanket',
    prod_Pk_Qty: 1,
    prod_Price: 8.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Gauze 50mm x 50mm - Non Sterile',
    prod_Code: '298575-001',
    prod_NAPI: '298575-001',
    prod_Description: 'Gauze 50mm x 50mm - Non Sterile',
    prod_Pk_Qty: 100,
    prod_Price: 14.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Gauze 75 mm x 75 mm - Non Sterile',
    prod_Code: '298576-001',
    prod_NAPI: '298576-001',
    prod_Description: 'Gauze 75 mm x 75 mm - Non Sterile',
    prod_Pk_Qty: 100,
    prod_Price: 21.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Needles - 18G x 38mm Disposable',
    prod_Code: '1003520-001',
    prod_NAPI: '1003520-001',
    prod_Description: 'Needles - 18G x 38mm Disposable',
    prod_Pk_Qty: 100,
    prod_Price: 34.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Needles - 20 G x 38 mm Disposable',
    prod_Code: '1003521-001',
    prod_NAPI: '1003521-001',
    prod_Description: 'Needles - 20 G x 38 mm Disposable',
    prod_Pk_Qty: 100,
    prod_Price: 34.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Needles - 21G x 38mm Disposable',
    prod_Code: '1003522-001',
    prod_NAPI: '1003522-001',
    prod_Description: 'Needles - 21G x 38mm Disposable',
    prod_Pk_Qty: 100,
    prod_Price: 34.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Needles - 22 G x 38 mm Disposable',
    prod_Code: '1003523-001',
    prod_NAPI: '1003523-001',
    prod_Description: 'Needles - 22 G x 38 mm Disposable',
    prod_Pk_Qty: 100,
    prod_Price: 34.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Needles - 23G x 25mm Disposable',
    prod_Code: '1003524-001',
    prod_NAPI: '1003524-001',
    prod_Description: 'Needles - 23G x 25mm Disposable',
    prod_Pk_Qty: 100,
    prod_Price: 34.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Needles - 26 G x 13 mm Disposable',
    prod_Code: '1003525-001',
    prod_NAPI: '1003525-001',
    prod_Description: 'Needles - 26 G x 13 mm Disposable',
    prod_Pk_Qty: 100,
    prod_Price: 34.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Needles - 27G x 13mm Disposable',
    prod_Code: '1003526-001',
    prod_NAPI: '1003526-001',
    prod_Description: 'Needles - 27G x 13mm Disposable',
    prod_Pk_Qty: 100,
    prod_Price: 34.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Plaster Roll - Fabric Adhesive 25 mm x 1 m',
    prod_Code: '1002417-001',
    prod_NAPI: '1002417-001',
    prod_Description: 'Plaster Roll - Fabric Adhesive 25 mm x 1 m',
    prod_Pk_Qty: 1,
    prod_Price: 8.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Plaster Roll - Fabric Adhesive 25mm x 3m',
    prod_Code: '1002418-001',
    prod_NAPI: '1002418-001',
    prod_Description: 'Plaster Roll - Fabric Adhesive 25mm x 3m',
    prod_Pk_Qty: 1,
    prod_Price: 17.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Paper Adhesive 12 mm x 3 m',
    prod_Code: '1002858-001',
    prod_NAPI: '1002858-001',
    prod_Description: 'Tape - Paper Adhesive 12 mm x 3 m',
    prod_Pk_Qty: 1,
    prod_Price: 5.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Paper Adhesive 12mm x 10m',
    prod_Code: '1002856-001',
    prod_NAPI: '1002856-001',
    prod_Description: 'Tape - Paper Adhesive 12mm x 10m',
    prod_Pk_Qty: 1,
    prod_Price: 10.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Paper Adhesive 24 mm x 3 m',
    prod_Code: '1002860-001',
    prod_NAPI: '1002860-001',
    prod_Description: 'Tape - Paper Adhesive 24 mm x 3 m',
    prod_Pk_Qty: 1,
    prod_Price: 7.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Paper Adhesive 24mm x 10m',
    prod_Code: '1002859-001',
    prod_NAPI: '1002859-001',
    prod_Description: 'Tape - Paper Adhesive 24mm x 10m',
    prod_Pk_Qty: 1,
    prod_Price: 16.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Paper Adhesive 48 mm x 3 m',
    prod_Code: '1002862-001',
    prod_NAPI: '1002862-001',
    prod_Description: 'Tape - Paper Adhesive 48 mm x 3 m',
    prod_Pk_Qty: 1,
    prod_Price: 12.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Paper Adhesive 48mm x 10m',
    prod_Code: '1002861-001',
    prod_NAPI: '1002861-001',
    prod_Description: 'Tape - Paper Adhesive 48mm x 10m',
    prod_Pk_Qty: 1,
    prod_Price: 26.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Paper Brown 12 mm x 3 m',
    prod_Code: '1002863-001',
    prod_NAPI: '1002863-001',
    prod_Description: 'Tape - Paper Brown 12 mm x 3 m',
    prod_Pk_Qty: 1,
    prod_Price: 5.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Paper Brown 24mm x 3m',
    prod_Code: '1002866-001',
    prod_NAPI: '1002866-001',
    prod_Description: 'Tape - Paper Brown 24mm x 3m',
    prod_Pk_Qty: 1,
    prod_Price: 7.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Paper Brown 24 mm x 10 m',
    prod_Code: '1002864-001',
    prod_NAPI: '1002864-001',
    prod_Description: 'Tape - Paper Brown 24 mm x 10 m',
    prod_Pk_Qty: 1,
    prod_Price: 16.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Surgical 12mm x 5m',
    prod_Code: '1002968-001',
    prod_NAPI: '1002968-001',
    prod_Description: 'Tape - Surgical 12mm x 5m',
    prod_Pk_Qty: 1,
    prod_Price: 7.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tape - Surgical - 24 mm x 5 m',
    prod_Code: '1002969-001',
    prod_NAPI: '1002969-001',
    prod_Description: 'Tape - Surgical - 24 mm x 5 m',
    prod_Pk_Qty: 1,
    prod_Price: 14.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Urine Bag 2L with Port',
    prod_Code: '1002960-001',
    prod_NAPI: '1002960-001',
    prod_Description: 'Urine Bag 2L with Port',
    prod_Pk_Qty: 1,
    prod_Price: 10.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Wound Strip - Sterile - 6 mm x 75 mm',
    prod_Code: '1011158-001',
    prod_NAPI: '1011158-001',
    prod_Description: 'Wound Strip - Sterile - 6 mm x 75 mm',
    prod_Pk_Qty: 1,
    prod_Price: 15.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Wound Strip -Sterile - 6mm x 75mm',
    prod_Code: '1011160-001',
    prod_NAPI: '1011160-001',
    prod_Description: 'Wound Strip -Sterile - 6mm x 75mm',
    prod_Pk_Qty: 5,
    prod_Price: 76.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Wound Strip - Sterile - 6 mm x 100 mm',
    prod_Code: '1011155-001',
    prod_NAPI: '1011155-001',
    prod_Description: 'Wound Strip - Sterile - 6 mm x 100 mm',
    prod_Pk_Qty: 1,
    prod_Price: 16.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Wound Strip - Sterile - 6mm x 100mm',
    prod_Code: '1011156-001',
    prod_NAPI: '1011156-001',
    prod_Description: 'Wound Strip - Sterile - 6mm x 100mm',
    prod_Pk_Qty: 5,
    prod_Price: 81.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Wound Strip - Sterile - 12 mm x 75 mm',
    prod_Code: '1011174-001',
    prod_NAPI: '1011174-001',
    prod_Description: 'Wound Strip - Sterile - 12 mm x 75 mm',
    prod_Pk_Qty: 1,
    prod_Price: 19.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Wound Strip - Sterile - 12mm x 75mm',
    prod_Code: '1011177-001',
    prod_NAPI: '1011177-001',
    prod_Description: 'Wound Strip - Sterile - 12mm x 75mm',
    prod_Pk_Qty: 5,
    prod_Price: 94.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Adjustable Support - Ankle - One Size',
    prod_Code: '1002025-001',
    prod_NAPI: '1002025-001',
    prod_Description: 'Adjustable Support - Ankle - One Size',
    prod_Pk_Qty: 1,
    prod_Price: 39.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Adjustable Support - Elbow - One Size',
    prod_Code: '1003494-001',
    prod_NAPI: '1003494-001',
    prod_Description: 'Adjustable Support - Elbow - One Size',
    prod_Pk_Qty: 1,
    prod_Price: 39.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Adjustable Support - Knee - One Size',
    prod_Code: '1002835-001',
    prod_NAPI: '1002835-001',
    prod_Description: 'Adjustable Support - Knee - One Size',
    prod_Pk_Qty: 1,
    prod_Price: 39.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Adjustable Support - Wrist - One Size',
    prod_Code: '1002971-001',
    prod_NAPI: '1002971-001',
    prod_Description: 'Adjustable Support - Wrist - One Size',
    prod_Pk_Qty: 1,
    prod_Price: 39.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 2.5 cm x 4.5 m - Black',
    prod_Code: '1011201-001',
    prod_NAPI: '1011201-001',
    prod_Description: 'Cohesive Wrap 2.5 cm x 4.5 m - Black',
    prod_Pk_Qty: 1,
    prod_Price: 7.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 2.5cm x 4.5m - Green',
    prod_Code: '1011202-001',
    prod_NAPI: '1011202-001',
    prod_Description: 'Cohesive Wrap 2.5cm x 4.5m - Green',
    prod_Pk_Qty: 1,
    prod_Price: 7.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 5 cm x 4.5 m - Black',
    prod_Code: '1011203-001',
    prod_NAPI: '1011203-001',
    prod_Description: 'Cohesive Wrap 5 cm x 4.5 m - Black',
    prod_Pk_Qty: 1,
    prod_Price: 14.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 5cm x 4.5m - Brown',
    prod_Code: '1011204-001',
    prod_NAPI: '1011204-001',
    prod_Description: 'Cohesive Wrap 5cm x 4.5m - Brown',
    prod_Pk_Qty: 1,
    prod_Price: 14.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 5 cm x 4.5 m - Green',
    prod_Code: '1011212-001',
    prod_NAPI: '1011212-001',
    prod_Description: 'Cohesive Wrap 5 cm x 4.5 m - Green',
    prod_Pk_Qty: 1,
    prod_Price: 14.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 5cm x 4.5m - Pink',
    prod_Code: '1011216-001',
    prod_NAPI: '1011216-001',
    prod_Description: 'Cohesive Wrap 5cm x 4.5m - Pink',
    prod_Pk_Qty: 1,
    prod_Price: 14.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 7.5 cm x 4.5 m - Black',
    prod_Code: '1011218-001',
    prod_NAPI: '1011218-001',
    prod_Description: 'Cohesive Wrap 7.5 cm x 4.5 m - Black',
    prod_Pk_Qty: 1,
    prod_Price: 19.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 7.5cm x 4.5m - Brown',
    prod_Code: '1011220-001',
    prod_NAPI: '1011220-001',
    prod_Description: 'Cohesive Wrap 7.5cm x 4.5m - Brown',
    prod_Pk_Qty: 1,
    prod_Price: 19.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 7.5 cm x 4.5 m - Green',
    prod_Code: '1011221-001',
    prod_NAPI: '1011221-001',
    prod_Description: 'Cohesive Wrap 7.5 cm x 4.5 m - Green',
    prod_Pk_Qty: 1,
    prod_Price: 19.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 7.5cm x 4.5m - Pink',
    prod_Code: '1011222-001',
    prod_NAPI: '1011222-001',
    prod_Description: 'Cohesive Wrap 7.5cm x 4.5m - Pink',
    prod_Pk_Qty: 1,
    prod_Price: 19.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 10 cm x 4.5 m - Black',
    prod_Code: '1011199-001',
    prod_NAPI: '1011199-001',
    prod_Description: 'Cohesive Wrap 10 cm x 4.5 m - Black',
    prod_Pk_Qty: 1,
    prod_Price: 23.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Cohesive Wrap 10cm x 4.5m - Brown',
    prod_Code: '1011200-001',
    prod_NAPI: '1011200-001',
    prod_Description: 'Cohesive Wrap 10cm x 4.5m - Brown',
    prod_Pk_Qty: 1,
    prod_Price: 23.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Support - Ankle - Small',
    prod_Code: '1001935-001',
    prod_NAPI: '1001935-001',
    prod_Description: 'Elastic Support - Ankle - Small',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Support - Ankle - Medium',
    prod_Code: '1001934-001',
    prod_NAPI: '1001934-001',
    prod_Description: 'Elastic Support - Ankle - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Support - Ankle - Large',
    prod_Code: '1002026-001',
    prod_NAPI: '1002026-001',
    prod_Description: 'Elastic Support - Ankle - Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Support - Ankle - Extra Large',
    prod_Code: '1001936-001',
    prod_NAPI: '1001936-001',
    prod_Description: 'Elastic Support - Ankle - Extra Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Elbow Support - Small',
    prod_Code: '1003498 - 001',
    prod_NAPI: '1003498 - 001',
    prod_Description: 'Elastic Elbow Support - Small',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Elbow Support - Medium',
    prod_Code: '1003497-001',
    prod_NAPI: '1003497-001',
    prod_Description: 'Elastic Elbow Support - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Elbow Support - Large',
    prod_Code: '1003495-001',
    prod_NAPI: '1003495-001',
    prod_Description: 'Elastic Elbow Support - Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Elbow Support - Extra Large',
    prod_Code: '1003501-001',
    prod_NAPI: '1003501-001',
    prod_Description: 'Elastic Elbow Support - Extra Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Knee Support - Small',
    prod_Code: '1002838-001',
    prod_NAPI: '1002838-001',
    prod_Description: 'Elastic Knee Support - Small',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Knee Support - Medium',
    prod_Code: '1002840-001',
    prod_NAPI: '1002840-001',
    prod_Description: 'Elastic Knee Support - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Knee Support - Large',
    prod_Code: '1002841-001',
    prod_NAPI: '1002841-001',
    prod_Description: 'Elastic Knee Support - Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Knee Support - Extra Large',
    prod_Code: '1002842-001',
    prod_NAPI: '1002842-001',
    prod_Description: 'Elastic Knee Support - Extra Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Thigh Support - Small',
    prod_Code: '1011168-001',
    prod_NAPI: '1011168-001',
    prod_Description: 'Elastic Thigh Support - Small',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Thigh Support - Medium',
    prod_Code: '1011167-001',
    prod_NAPI: '1011167-001',
    prod_Description: 'Elastic Thigh Support - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Thigh Support - Large',
    prod_Code: '1011165-001',
    prod_NAPI: '1011165-001',
    prod_Description: 'Elastic Thigh Support - Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Thigh Support - Extra Large',
    prod_Code: '1011169-001',
    prod_NAPI: '1011169-001',
    prod_Description: 'Elastic Thigh Support - Extra Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Wrist Support - Small',
    prod_Code: '1002976-001',
    prod_NAPI: '1002976-001',
    prod_Description: 'Elastic Wrist Support - Small',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Wrist Support - Medium',
    prod_Code: '1002975-001',
    prod_NAPI: '1002975-001',
    prod_Description: 'Elastic Wrist Support - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Wrist Support - Large',
    prod_Code: '1002972-001',
    prod_NAPI: '1002972-001',
    prod_Description: 'Elastic Wrist Support - Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Elastic Wrist Support - Extra Large',
    prod_Code: '1002984-001',
    prod_NAPI: '1002984-001',
    prod_Description: 'Elastic Wrist Support - Extra Large',
    prod_Pk_Qty: 1,
    prod_Price: 29.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Kinesio Tape 50 x 5 m - Black',
    prod_Code: '1002849-001',
    prod_NAPI: '1002849-001',
    prod_Description: 'Kinesio Tape 50 x 5 m - Black',
    prod_Pk_Qty: 1,
    prod_Price: 45.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Kinesio Tape 50 x 5m - Blue',
    prod_Code: '1002851-001',
    prod_NAPI: '1002851-001',
    prod_Description: 'Kinesio Tape 50 x 5m - Blue',
    prod_Pk_Qty: 1,
    prod_Price: 45.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Kinesio Tape 50 x 5 m - Pink',
    prod_Code: '1002852-001',
    prod_NAPI: '1002852-001',
    prod_Description: 'Kinesio Tape 50 x 5 m - Pink',
    prod_Pk_Qty: 1,
    prod_Price: 45.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Kinesio Tape 75 x 5m - Black',
    prod_Code: '1002853-001',
    prod_NAPI: '1002853-001',
    prod_Description: 'Kinesio Tape 75 x 5m - Black',
    prod_Pk_Qty: 1,
    prod_Price: 59.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Kinesio Tape 75 x 5 m - Blue',
    prod_Code: '1002857-001',
    prod_NAPI: '1002857-001',
    prod_Description: 'Kinesio Tape 75 x 5 m - Blue',
    prod_Pk_Qty: 1,
    prod_Price: 59.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Kinesio Tape 75 x 5m - Pink',
    prod_Code: '1002855-001',
    prod_NAPI: '1002855-001',
    prod_Description: 'Kinesio Tape 75 x 5m - Pink',
    prod_Pk_Qty: 1,
    prod_Price: 59.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Magnetic Ankle Neoprene Support - One Size',
    prod_Code: '1011171-001',
    prod_NAPI: '1011171-001',
    prod_Description: 'Magnetic Ankle Neoprene Support - One Size',
    prod_Pk_Qty: 1,
    prod_Price: 59.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Magnetic Elbow Neoprene Support - One Size',
    prod_Code: '1011208-001',
    prod_NAPI: '1011208-001',
    prod_Description: 'Magnetic Elbow Neoprene Support - One Size',
    prod_Pk_Qty: 1,
    prod_Price: 69.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Magnetic Knee Neoprene Support - One Size',
    prod_Code: '1011159-001',
    prod_NAPI: '1011159-001',
    prod_Description: 'Magnetic Knee Neoprene Support - One Size',
    prod_Pk_Qty: 1,
    prod_Price: 99.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Magnetic Wrist Neoprene Support - One Size',
    prod_Code: '1011161-001',
    prod_NAPI: '1011161-001',
    prod_Description: 'Magnetic Wrist Neoprene Support - One Size',
    prod_Pk_Qty: 1,
    prod_Price: 49.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Ankle Support - Small',
    prod_Code: '1001943-001',
    prod_NAPI: '1001943-001',
    prod_Description: 'Neoprene Premium Ankle Support - Small',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Ankle Support - Medium',
    prod_Code: '1001942-001',
    prod_NAPI: '1001942-001',
    prod_Description: 'Neoprene Premium Ankle Support - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Ankle Support - Large',
    prod_Code: '1001941-001',
    prod_NAPI: '1001941-001',
    prod_Description: 'Neoprene Premium Ankle Support - Large',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Ankle Support - Extra Large',
    prod_Code: '1002182-001',
    prod_NAPI: '1002182-001',
    prod_Description: 'Neoprene Premium Ankle Support - Extra Large',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Elbow Support - Small',
    prod_Code: '1002413-001',
    prod_NAPI: '1002413-001',
    prod_Description: 'Neoprene Premium Elbow Support - Small',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Elbow Support - Medium',
    prod_Code: '1002411-001',
    prod_NAPI: '1002411-001',
    prod_Description: 'Neoprene Premium Elbow Support - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Elbow Support - Large',
    prod_Code: '1003508 - 001',
    prod_NAPI: '1003508 - 001',
    prod_Description: 'Neoprene Premium Elbow Support - Large',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Elbow Support - Extra Large',
    prod_Code: '1002414-001',
    prod_NAPI: '1002414-001',
    prod_Description: 'Neoprene Premium Elbow Support - Extra Large',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Knee Support - Small',
    prod_Code: '1003527 - 001',
    prod_NAPI: '1003527 - 001',
    prod_Description: 'Neoprene Premium Knee Support - Small',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Knee Support - Medium',
    prod_Code: '1003923-001',
    prod_NAPI: '1003923-001',
    prod_Description: 'Neoprene Premium Knee Support - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Knee Support - Large',
    prod_Code: '1002847-001',
    prod_NAPI: '1002847-001',
    prod_Description: 'Neoprene Premium Knee Support - Large',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Knee Support - Extra Large',
    prod_Code: '1003528-001',
    prod_NAPI: '1003528-001',
    prod_Description: 'Neoprene Premium Knee Support - Extra Large',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Wrist Support - Small',
    prod_Code: '1003000-001',
    prod_NAPI: '1003000-001',
    prod_Description: 'Neoprene Premium Wrist Support - Small',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Wrist Support - Medium',
    prod_Code: '100299-001',
    prod_NAPI: '100299-001',
    prod_Description: 'Neoprene Premium Wrist Support - Medium',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Wrist Support - Large',
    prod_Code: '1002998-001',
    prod_NAPI: '1002998-001',
    prod_Description: 'Neoprene Premium Wrist Support - Large',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Neoprene Premium Wrist Support - Extra Large',
    prod_Code: '1002996-001',
    prod_NAPI: '1002996-001',
    prod_Description: 'Neoprene Premium Wrist Support - Extra Large',
    prod_Pk_Qty: 1,
    prod_Price: 44.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Patella Wrap',
    prod_Code: '1011162-001',
    prod_NAPI: '1011162-001',
    prod_Description: 'Patella Wrap',
    prod_Pk_Qty: 1,
    prod_Price: 39.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'Tennis Elbow Wrap',
    prod_Code: '1011163-001',
    prod_NAPI: '1011163-001',
    prod_Description: 'Tennis Elbow Wrap',
    prod_Pk_Qty: 1,
    prod_Price: 39.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'ALCOHOL BREATH TESTER',
    prod_Code: '97467-001',
    prod_NAPI: '97467-001',
    prod_Description: 'ALCOHOL BREATH TESTER',
    prod_Price: 39.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: '5 - DRUG TEST PANEL(DIP)',
    prod_Code: '1002155-001',
    prod_NAPI: '1002155-001',
    prod_Description: '5 - DRUG TEST PANEL(DIP)',
    prod_Price: 39.95,
    prod_Disc: 10,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: '6 - DRUG TEST DEVICE(DROP)',
    prod_Code: '1002157-001',
    prod_NAPI: '1002157-001',
    prod_Description: '6 - DRUG TEST DEVICE(DROP)',
    prod_Price: 39.95,
    prod_Disc: 15,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'HIV COMPLETE TEST KIT',
    prod_Code: '151616-003',
    prod_NAPI: '151616-003',
    prod_Description: 'HIV COMPLETE TEST KIT',
    prod_Price: 39.95,
    prod_Disc: 15,
    prod_Category: '',
    prod_Active: '1'
  }),
  new Product({
    prod_Name: 'MALARIA(PF / PAN) COMPLETE TEST KIT',
    prod_Code: '297466-001',
    prod_NAPI: '297466-001',
    prod_Description: 'MALARIA(PF / PAN) COMPLETE TEST KIT',
    prod_Price: 39.95,
    prod_Disc: 0,
    prod_Category: '',
    prod_Active: '1'
  })
];

var done = 0;
for (var i = 0; i < products.length; i++) {
  products[i].save(function(err, result) {
    done++;
    if (err) {
      console.log(err);
    }
    if (done === products.length) {
      exit();
    }
  });
}

function exit() {
  mongoose.disconnect();
}
